# Use the official Node.js 16 image.
# Check for the latest version on https://hub.docker.com/_/node/
FROM node:18

# Create and change to the app directory.
WORKDIR /usr/src/app

# Install pnpm
RUN npm install -g pnpm

# Copy the package.json and pnpm-lock.yaml files (if you have one).
# This will allow Docker to cache the installed modules and speed up builds.
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile 

# Copy the rest of your application code
COPY . .

# Build the app (optional, you can customize this according to your needs)
RUN pnpm run build

EXPOSE 8080
# Command to run your app using Vite
CMD ["pnpm", "run", "preview"]

